name: 'Pull Secrets'
description: 'Pulls secrets from from Hashicorp Key Vault '
inputs:
  url:
    description: 'enterprise vault service endpoint'
    required: true
  namespace:
    description: 'labs namespace'
    default: 'ushi/innovate'
    required: true 
  approleId:
    description: 'approleId'
    required: true
  secretId:
    description: 'secretId'
    required: true
  secrets:
    description: 'version'
    required: true
  
# outputs:
#   es-auth-token: # id of output
#     description: 'elasticsearch auth token'

runs:
  using: 'docker'
  image: 'Dockerfile'

